[package]
name = "noise"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
repository = "https://github.com/pipedown/noise.git"
homepage = "https://github.com/pipedown/noise.git"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Nested Object Inverted Search Engine"

[dependencies]
rocksdb = "0.4.1"
